<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/Introduccion_a_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy

Numpy (Numerical Python) es un paquete estándar para trabajar con arrays (matrices y vectores)

In [ ]:
# Importación

import numpy as np # np es un alias para llamar más rápido a NumPy

## NumPy vs list

Lista de Python

- Puede contener elementos de de distinto tipo

Array de Numpy
- Muy eficiente
- Ocupa menos memoria
- Permite muchas operacinoes matematicas


In [ ]:
# Diferencias entre NumPy y las listas

my_list = [5, "seven", 20, True]

print(my_list)
print(my_list[0])
print(my_list[1])
print(my_list[3])

my_array_1 = np.array([5, "seven", 20, True]) # Es importante saber que numpy solo permite un único tipo de dato dentro del array, por lo que si tenemos varios tipos diferentes los convertira en string
print(my_array_1)

my_array_2 = np.array([5, 10, 20, 5.2]) # Si mezclamos enteros con decimales, numpy lo pasara todos a decimales
print(my_array_2)

my_array_3 = np.array([5, 10, 20, 4]) # Aquí todos los numeros serán de tipo entero
print(my_array_3)


[5, 'seven', 20, True]
5
seven
True
['5' 'seven' '20' 'True']
[ 5.  10.  20.   5.2]
[ 5 10 20  4]


In [ ]:
# Ahora vamos a imprimir cada typo de los emplemos anteriores

print(type(my_array_1))
print(type(my_array_2))
print(type(my_array_3))

# Para saber cuanto ocupa cada tipo (string, int, floot) en memoria
print(my_array_1.dtype)
print(my_array_2.dtype)
print(my_array_3.dtype)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<U21
float64
int64


# Arrays de una dimensión

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a[0])
print(a[1])
print(a[-1])

[1 2 3 4 5 6]
1
2
6


## Arrays de dos dimensiones

In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # Es importante que nunca falte un dato, es decir, si tenemos 3 array con 4 datos en cada uno, debe de cumplirse esta condición en todos los array
print(b)


(3, 4)


## Dimensiones del array

In [ ]:
array_3d = np.array([[[0,1,2,3],
                      [4,5,6,7]],
                     
                     [[0,1,2,3],
                      [4,5,6,7]],
                     
                     [[0,1,2,3],
                      [4,5,6,7]]
                    ])
print(array_3d)
print(array_3d.ndim)  # Con ndim podemos sacar el numero de dimensiones que tiene el array
print(array_3d.size)  # Con size nos da la cantidad de datos que tenemos dentro del array
print(array_3d.shape) # Con shape(forma) nos saca las filas, columnas y dimensiones que tiene el array

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
3
24
(3, 2, 4)


## Creación de arrays básicos

In [ ]:
num_0 = np.zeros(10) # Esto crea un array con 10 ceros de tipo float
print(num_0)

num_0 = np.zeros(10, int) # Esto crea un array con 10 ceros de tipo entero
print(num_0)

num_1 = np.ones(10)  # Esto crea un array con 10 unos de tipo float
print(num_1 )

num_1 = np.ones(10, int)  # Esto crea un array con 10 unos de tipo entero
print(num_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [ ]:
# Creación de array con cualquier numero que numpy decida

a = np.empty(10)
print(a)
print(a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [ ]:
# Array de 2 dimensiones con np.empty

np.empty([10, 3]) # Esto genera un array de 2 dimensiones con 3 array


array([[1.73131432e-316, 9.68368666e-322, 0.00000000e+000],
       [0.00000000e+000, 8.48798316e-314, 3.16251369e+180],
       [1.72132957e+243, 2.59042262e-144, 2.03890423e+180],
       [7.11050780e-038, 7.37108894e+228, 1.04796651e-142],
       [2.59032018e-144, 2.86530729e+161, 2.11329502e+214],
       [7.49511203e+247, 1.12284826e+219, 1.94919754e-153],
       [3.50896888e+151, 2.59903818e-144, 4.97750675e+151],
       [9.08367206e+223, 1.48890323e+195, 2.59042349e-144],
       [6.34910904e+151, 3.68777431e+180, 1.17146537e+214],
       [8.76730942e+252, 2.59903831e-144, 6.91802220e-310]])

In [ ]:
# Bucles con Numpy

np.arange(12) # Crea un array que empieza en el 0 y acaba en el 11


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(10, 20) # Crea un array que empieza en el 10 y acaba en el 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10, 30, 2) # Crea un array que empieza en el 10 y acaba en el 28, y en cada salto lo hace *2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# Devolver números espaciados uniformemente en un intervalo especificado

np.linspace(-10, 10, num = 5)

array([-10.,  -5.,   0.,   5.,  10.])

In [ ]:
# Devolver números espaciados uniformemente en un intervalo especificado y con el tipo que deseemos

np.linspace(-10, 10, num = 5, dtype = int) #(init, finish, interval, type)

array([-10,  -5,   0,   5,  10])

## Ejercicio 1

Crea una función equivalente a `ones` con la siguiente cabecera que rellene un array con unos

```
def my_ones(n):
  pass
```

In [ ]:
def my_ones(n):

  ones_array = []

  for i in range(n):
    ones_array.append(float(1))
  
  ones_array = np.array(ones_array)
  return ones_array

print(my_ones(7))

# Ejercicio Oscar

def my_ones_oscar(n):
  return np.array(1 for i in range(n))

[1. 1. 1. 1. 1. 1. 1.]


## Ejercicio 2

Crea una función con la siguiente cabecera que rellene un array con números consecutivos primos empezando por el 1.

```
def numpy_primes(n):
  pass
```

In [ ]:
def numpy_primes(n):

  mi_lista = []

  def primo(numero):
    if numero == 0 or numero == 1 or numero == 4:
        return False
    for x in range(2, int(numero/2)):
        if numero % x == 0:
            return False
    return numero

  for i in range(n):
    is_prime = primo(i)
    if is_prime != 0:
      mi_lista.append(float(is_prime))

  mi_lista = np.array(mi_lista)

  return mi_lista

print(numpy_primes(7))

[2. 3. 5.]


## Ordenación 

In [ ]:
# Ordena los numeros en c y los imprime como int
c = np.array([2,1,5,3,7,6,4,8])
np.sort(c)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Ordena los strings en c y los imprime como string
c = np.array(["d", "c", "b","a"])
np.sort(c)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [ ]:
# Ordena de forma inversa los numeros en c y los imprime como int
c = np.array([2,1,5,3,7,6,4,8])
np.sort(c)[::-1] # [init_position : last_position : salt_positions]

array([8, 7, 6, 5, 4, 3, 2, 1])

## Añadir y quitar trozos

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array(
            [[1, 2], 
             [3, 4]]
)

y = np.array([[5, 6]]) # Arrya de 2 dimensiones

print(x)
print(y)

# Ahora concatenamos
z = np.concatenate((x, y))
print(z)

# También se puede hacer así
z = x + y
print(x + y)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.arange(16) # Crea un array desde el 0 hasta el 15
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
print(a[2:]) # Saca desde la posición 2 hasta la 
print(a[:-4]) # Casa desde la posición 0 hasta la -4 sin incluir esta última
print(a[-3:-7:-1]) # Saca de forma inversa de 1 en 1 desde la posición -3 hasta la posición -7 sin incluir esta última

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[13 12 11 10]


In [ ]:
data = np.array(
    [[1,2],
     [3,4],
     [5, 6]]
)

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Sacamos el valor de la posición 1 del array en la posición 0
data[0, 1]

2

In [ ]:
# Sacamos los arrays de la posición 1 a la 3 sin incluir la 3
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
# Sacamos los valores en la posición 1 de los 2 primeros arrays
data[0:2, 1]

array([2, 4])

In [ ]:
a = np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Reshape crea subarrays de un array según las filas y las columnas que le pasemos
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a = np.arange(100, 112)
print(a)

[100 101 102 103 104 105 106 107 108 109 110 111]


In [ ]:
# Aquí menos -1 hace el calculo automatico de columnas
b = a.reshape(4, -1)
print(b)

[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]


## Filtros

In [ ]:
a = np.array([[1, 2, 3, 4], [6, 7, 8, 9], [10, 11, 12, 13]])
print(a)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
# Con esta operación sacamos los valores menores de 5 que estan dentro del array

print(a[a < 5])

[1 2 3 4]


In [ ]:
# Con esto sacamos todos los valores en booleano dentro del array que cumplen la condición

print([a < 5])

[array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])]


In [ ]:
five_up = (a >= 5)
print(a[five_up])

[ 6  7  8  9 10 11 12 13]


In [ ]:
import sympy as sp

es_primo = sp.isprime(a) # INVESTIGAR!!!!!
es_par = (a % 2 == 0)
print(a[es_primo])

[]


In [ ]:
c = a [(a > 2) & (a < 11)]
print(c)

c = a [((a % 2) == 0) & (a < 11)]
print(c)

[ 3  4  6  7  8  9 10]
[ 2  4  6  8 10]


In [ ]:
# Aquí sacamos los que están suspensos y aprobados con booleans y despues sacamos el array solo con los aprobados
marks = np.array([4, 7, 8, 5, 10, 3, 2])
passed = marks >= 5
print(passed)
print(marks[passed])

[False  True  True  True  True False False]
[ 7  8  5 10]


## Mezcla de índices

In [ ]:
a = np.array([4, 8, 20, 21, 31, 44, 7, 9, 13])
b = np.array([4, 2, 0, 3])
print(a)
print(b)

[ 4  8 20 21 31 44  7  9 13]
[4 2 0 3]


In [ ]:
# Esto saca las posiciones del array a según las posiciones pasadas en el array b.
print(a[b])

[31 20  4 21]


## Operaciones con arrays

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)

In [ ]:
data + ones

array([2, 3])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * ones

array([1, 2])

In [ ]:
data * data


array([1, 4])

In [ ]:
data / data 

array([1., 1.])

In [ ]:
data // data

array([1, 1])

In [ ]:
# Para ver el maximo, minimo y la suma total

a = np.arange(5, 15)
print(a.sum())
print(a.min())
print(a.max())

95
5
14


In [ ]:
b = np.array([[1, 1],
              [2, 2]])
print(b)

[[1 1]
 [2 2]]


In [ ]:
# Aqui sumamos columnas
print(b.sum(axis = 0))

[3 3]


In [ ]:
# Aquí sumamos filas
print(b.sum(axis = 1))

[2 4]


In [ ]:
# Aquí multiplicamos con decimales
data = np.array([1., 2.])
print(data * 1.6)

[1.6 3.2]


In [ ]:
np.set_printoptions(suppress = True)
np.array([0.01, 0.004])

array([0.01 , 0.004])

## Arrays aleatorios

In [ ]:
# con np.random.default_rng generamos numeros aleatorios, si dentro del parentesis () indicamos un numero lo hara desde ese numero
rng = np.random.default_rng()

In [ ]:
# Aquí generamos un array de 3 filas por 4 columnas con numeros aleatorios
a = rng.integers(11, size = (3, 4))
print(a)

[[ 8 10  6  4]
 [ 0  0  7  5]
 [ 1  1  6  1]]


In [ ]:
a = rng.random((3, 4))
print(a)

[[0.84887153 0.60551402 0.29525264 0.81959391]
 [0.09960427 0.22972647 0.99906763 0.79169301]
 [0.71548842 0.42578372 0.92763661 0.68758441]]


In [ ]:
a = np.random.randint(100, 201, size = 20)
print(a)

[127 116 125 175 126 136 109 170 115 198 187 160 118 117 148 150 123 191
 103 150]
