<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/Numpy_bonus_arrays_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importacion de Numpy

In [1]:
import numpy as np

# Bonus Exercices Array 3

[Enlace](https://www.w3resource.com/python-exercises/numpy/index-array.php)

## Ejercicio 61

Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.

In [2]:
# Creamos el array de 14 elementos

array_14_elements = np.random.randint(0, 100, size = 14)
print(array_14_elements)

[99 64 39 75 14 78 85 31 95 57 50 45 63 75]


In [3]:
# A continuación dividimos el array en 3 arrays, uno de 2, otro de 4 y otro de 8

""" 

    El funcionamiento de .split es el siguiente:
      -En el primer parametro pasamos el array que queremos seccionar.
      -El segundo parametro indicamos las divisiones que se haran en 
       forma de split, para el caso de los valores que pasamos seríia
       asíi:
       
       ary[:2]
       ary[2:6]
       ary[6:] 


"""
my_array_split = np.split(array_14_elements, [2, 6])
print(my_array_split)

[array([99, 64]), array([39, 75, 14, 78]), array([85, 31, 95, 57, 50, 45, 63, 75])]


## Ejercicio 62

Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis



In [4]:
# Creamos el array.

array_spl = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[12, 13, 14, 15]])
print(array_spl)

np.hsplit(array_spl, [2, 6])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]), array([], shape=(4, 0), dtype=int64)]

## Ejercicio 63

Write a NumPy program to get the number of nonzero elements in an array

In [5]:
# Cremos el array con numeros que tengan ceros.

my_array = np.asarray([10, 1000, 250, 500, 0]) # el 0 solo no se cuenta.

np.count_nonzero(my_array)

4

## Ejercicio 64

Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4

In [6]:
# Primero vamos a crear un array de ceros

array_zeros = np.zeros([5, 5])
print(array_zeros, "\n")

# Ahora concatenemos e iigualamos con un arange

array_zeros += np.arange(5)

print(array_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Ejercicio 65

Write a NumPy program to test whether specified values are present in an array


In [7]:
# Creamos el array

array_random_1 = np.random.randint(0, 100, size = 10)

print(array_random_1, "\n")

# Con isin, miramos si alguno de los valores que le pasamos como segundo parametro estan en nuestro array.

array_random_1[np.isin(array_random_1, [10, 23, 12, 65, 50])]

[12 44  9 88 64 37  1 97 89 54] 



array([12])

## Ejercicio 66

Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded

In [8]:
# Creamos el array con 10 numeros del 0 al 1 sin incluir ninguno de los 2.

num_randoms = np.random.rand(10)
print(num_randoms)

[0.71768542 0.98273936 0.75901579 0.29053598 0.50436071 0.88757603
 0.20367576 0.702631   0.30743544 0.29883213]


## Ejercicio 67

Write a NumPy program to make an array immutable (read-only)

In [9]:
# Creamos un array que despues haremos que solo pueda ser leido y no modificado

array_immutable = np.random.randint(0, 20, size = 20)

print(array_immutable, "\n")

# Ahora convertimos el array en Immutable

array_immutable.flags.writeable = False

# Probamos que no se puede sobrescribir

array_immutable[0] = 20

[19  4 13  7  1  0  8  0 12  3  9 13  9  3  3  5 12 13  6 17] 



ValueError: ignored

## Ejecicio 68

Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100

In [10]:
# Creamos un array 

my_array = np.arange(0, 100)

# Sacamos los multiplos de 3 y de 5

multiply_array = my_array[(my_array % 3 == 0) | (my_array % 5 == 0)]

print(multiply_array.sum())

2318


## Ejercicio 69

Write a NumPy program to create an array with 10^3 elements.

In [11]:
# Creamos el array

array_2 = np.arange(0, 10)

print(array_2, "\n")

# A continuación lo elevamos a al cubo ^ 3

array_power = np.power(array_2, 3)

print(array_power)

[0 1 2 3 4 5 6 7 8 9] 

[  0   1   8  27  64 125 216 343 512 729]


## Ejercicio 70

Write a NumPy program to create display every element of a NumPy array

In [12]:
# Creamos el array

my_array = np.random.randint(0, 1000, size = 20).reshape(5, 4)

print(my_array, '\n')

# Ahora mostramos cada numero dentro del array

for number in np.nditer(my_array):
    print(number, end = ' ')

[[588 459 597  53]
 [650 532 964 461]
 [789 250  25 216]
 [974 326 536 707]
 [951 584 777 865]] 

588 459 597 53 650 532 964 461 789 250 25 216 974 326 536 707 951 584 777 865 

## Ejercicio 71

Write a NumPy program to create and display every element of a NumPy array in Fortran order



In [13]:
# Creamos un array 

disorder_array = np.random.randint(0, 100, size = 20).reshape(5, 4)

print(disorder_array, '\n')

# El orden/array de Fortran es un caso especial en el que todos los elementos de un array se almacenan en orden columna-mayor.

for number in np.nditer(disorder_array, order = "F"):
    print(number, end = ' ')

[[29 72 44 84]
 [85  8 12 69]
 [44 36 99 96]
 [90 45 74 21]
 [80 11 58 35]] 

29 85 44 90 80 72 8 36 45 11 44 12 99 74 58 84 69 96 21 35 

## Ejercicio 72

Write a NumPy program to create a 5x5x5 cube of 1's

In [14]:
# Creamos un cubo de 5x5x5

cube_five = np.ones((5, 5, 5))

print(cube_five)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## Ejercicio 73

Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array. 

In [15]:
# Creamos el array

nuevo_array = np.arange(0, 12).reshape(3, 4)

print(nuevo_array, "\n")

multiply_3 = np.multiply(nuevo_array, 3)

print(multiply_3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## Ejercico 74

Write a NumPy program to combine a one and a two dimensional array together and display their elements

In [16]:
# Creamos 2 array, uno de 1 dimensión y otro de 2

array_1D = np.arange(0, 5)

array_2D = np.array([np.random.randint(0, 100, size = 5), np.arange(10, 15)])

print(array_1D, "\n")
print(array_2D, "\n")

# Ahora unimos el array 1D con el array 2D

union_array = np.union1d(array_1D, array_2D)

print(union_array)

[0 1 2 3 4] 

[[61 40 18 40  3]
 [10 11 12 13 14]] 

[ 0  1  2  3  4 10 11 12 13 14 18 40 61]


## Ejercicio 75

Write a NumPy program to create an array of zeros and three column types (integer, float, character)

In [25]:
# Creamos el array de ceros

zero_array = np.zeros((3), dtype=('i4,f4,a40'))

# Creamos una lista con 3 tipos de datos

three_distin_list = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]

# Ahora sustituimos el contenido de zero_array por los datos de la lista

zero_array[:] = three_distin_list

print(zero_array)

[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


## Ejercicio 76

 Write a NumPy program to create a function cube which cubes all the elements of an array

In [27]:
# Creamos un array

elevate_array = np.array([2, 4, 6, 8])

# Ahora hacemos la operación para elevarlos al cubo

elevate_array_result = np.power(elevate_array, 3)

print(elevate_array_result)

[  8  64 216 512]


## Ejercicio 77

Write a NumPy program to create an array of (3, 4) shape and convert the array elements in smaller chunks.

In [28]:
# Creamos el array de 3 x 4

array_matrix = np.array([[0, 1, 2, 3], [5, 6, 7, 8], [9, 10, 11, 12]])

print(array_matrix, '\n')

# Ahora lo volcamos como si levantasemos una L

for number in np.nditer(array_matrix, flags=['external_loop'], order='F'):
  print(number)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[0 5 9]
[ 1  6 10]
[ 2  7 11]
[ 3  8 12]


## Ejercicio 78

Write a NumPy program to create a record array from a (flat) list of arrays

In [24]:
# Creamos varios array

array_1 = np.array([1, 2, 3, 4])
array_2 = np.array(['Juan', 'Angel', 'Miguel', 'Elena'])
array_3 = np.array([70., 80., 78., 60.])

# Ahora combinamos los arrays

combinacion = np.core.records.fromarrays([array_1, array_2, array_3], names = ('index', 'nombre', 'peso'))

print(combinacion)

[(1, 'Juan', 70.) (2, 'Angel', 80.) (3, 'Miguel', 78.) (4, 'Elena', 60.)]


## Ejercicio 79

Write a NumPy program to generate a generic 2D Gaussian-like array

In [18]:
# !Repasar este concepto
# Creamos los arrays 

x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

d = np.sqrt(x * x + y * y)

sigma, mu = 1.0, 0.0

g = np.exp(-( (d - mu) ** 2 / ( 2.0 * sigma ** 2 ) ) )

print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## Ejercicio 80

Write a NumPy program to convert a NumPy array into Python list structure.

In [ ]:
# Creamos el array

new_array = np.random.randint(0, 100, size = 10, dtype = np.int16)

print(new_array)

[29 95 83 98 24 21 53 62 97 23]


In [ ]:
# Ahora pasamos el array a lista

new_list = new_array.tolist()

print(new_list, "\n")
print(type(new_list))

[29, 95, 83, 98, 24, 21, 53, 62, 97, 23] 

<class 'list'>


## Ejercicio 81

Write a NumPy program to access an array by column

In [ ]:
# Creamos el array y filtramos por columnas

array_access = np.array([[2, 3, 4, 5], [8, 9, 10, 11], [12, 13, 14, 15]])

print(array_access[:,0])
print(array_access[:,1])
print(array_access[:,2])
print(array_access[:,3])

[ 2  8 12]
[ 3  9 13]
[ 4 10 14]
[ 5 11 15]


## Ejercicio 82

Write a NumPy program to convert a NumPy array of float values to a NumPy array of integer values

In [ ]:
# Creamos un array con flotantes

array_float = np.array([1, 2, 3, 4], dtype = np.float16)

print(array_float, '\n')

# A continuación le cambiamos el tipo de dato a int (entero)

array_convert = array_float.astype(int)

print(array_convert)

[1. 2. 3. 4.] 

[1 2 3 4]


## Ejercicio 83

Write a NumPy program to display NumPy array elements of floating values with given precision.

In [ ]:
# Creamos un arra de entre 0 a 1

array_random = np.random.rand(10)

print(array_random, '\n')

[0.7  0.86 0.36 0.82 0.65 0.96 0.13 0.88 0.7  0.92] 



In [ ]:
# Ahora ajustamos la preción de los decimales, por ejemplo a 1

np.set_printoptions(precision = 1)

print(array_random)

[0.7 0.9 0.4 0.8 0.6 1.  0.1 0.9 0.7 0.9]


## Ejercicio 84

Write a NumPy program to suppresses the use of scientific notation for small numbers in NumPy array.

In [ ]:
# Creamos un array con numeros cientificos

array_supress = np.array([1.8e-10, 1.586, 150.45, 0.2855])

# Ahora pasamos los numeros cientificos a numeros normales

np.set_printoptions(precision = 2, suppress = True)

print(array_supress)

[  0.     1.59 150.45   0.29]


## Ejercicio 85

Write a NumPy program to create a NumPy array of 10 integers from a generator.

In [ ]:
# Creamos un array de 10 enteros

array_gen_int = np.random.randint(0, 100, size = 10)

print(array_gen_int)

[36  3 55 20 76 36 43 34 92 60]


## Ejercicio 86

Write a NumPy program to add an extra column to a NumPy array.

In [ ]:
# Creamos un array

extra_array = np.arange(0, 10, dtype = np.int8).reshape(5, 2)

print(extra_array)

# Ahora agregamos una nueva columna

add_colum_array = np.append(extra_array, [[5], [2], [3], [4], [1]], axis = 1)

print(add_colum_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 5]
 [2 3 2]
 [4 5 3]
 [6 7 4]
 [8 9 1]]


## Ejercicio 87

Write a NumPy program to find unique rows in a NumPy array

In [ ]:
# Creamos el array

find_array = np.array([[20, 20, 20, 0],
                      [0, 20, 20, 20],
                      [0, 20, 20, 20],
                      [20, 20, 20, 0],
                      [10, 20, 20,20]])

# Ahora aplicamos el metodo .unique a las filas para sacar los valores unicos

filter = np.unique(find_array, axis = 0)

print(filter)

[[ 0 20 20 20]
 [10 20 20 20]
 [20 20 20  0]]


## Ejercicio 88

Write a NumPy program to replace all elements of NumPy array that are greater than specified array

In [ ]:
# Creamos un array

my_array = np.random.randint(0, 100, size = 20)

print(my_array)

my_array[(my_array > 70)] = 0

print(my_array)


[96 19 78  5 65 15 84 45 29 81 63 85  6 85 37 57 15 93 49 52]
[ 0 19  0  5 65 15  0 45 29  0 63  0  6  0 37 57 15  0 49 52]


## Ejercicio 89

Write a NumPy program to remove specific elements in a NumPy array.

In [ ]:
# Creamos un array

drop_array = np.asarray([2, 3, 4, 5, 6, 7], dtype = np.int8)

print(drop_array)

# Ahora eliminamos algunos elementos del array, por ejemplo el 4 y el 6

new_array = np.delete(drop_array, [2, 4])

print(new_array)



[2 3 4 5 6 7]
[2 3 5 7]


## Ejercicio 90

Write a NumPy program to replace the negative values in a NumPy array with 0.

In [ ]:
# Creamos un array con negativos

array_negative = np.arange(-10, 10)

print(array_negative)

# Arora reemplazamos los numeros negativos por 0

array_negative[array_negative < 0] = 0

print(array_negative)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[0 0 0 0 0 0 0 0 0 0 0 1 2 3 4 5 6 7 8 9]


## Ejercicio 91

Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

In [ ]:
# Creamos un array con nan (not a number)

array_nan = np.array([10, np.nan, 20, 30, np.nan])

print(array_nan, '\n')

# Ahora limpiamos los nan de nuestro array

clean_nan = array_nan[np.logical_not(np.isnan(array_nan))]

print(clean_nan)

[10. nan 20. 30. nan] 

[10. 20. 30.]


## Ejercicio 92

Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

In [ ]:
# Creamos 2 array, 1 con numeros y otro con nombres
array_age = np.array([10, 20, 30, 40])

array_names = np.array(['Ariel', 'Sofia', 'Jasmin', 'Elena'])

# Ahora vamos a sacar a Ariel y a Jasmin, usando como referencia el array de age

filter = array_names[(array_age < 20) | (array_age == 30)]

print(filter)

['Ariel' 'Jasmin']


## Ejercicio 93

Write a NumPy program to get the magnitude of a vector in NumPy.

In [ ]:
# Creamos el array

mag_array = np.array([1, 35, 12, 56, 99])

# Ahora sacamos la magnitud del array que acabos de crear, para ello usaremos linalg.norm()

cal_mag_array = np.linalg.norm(mag_array)
print(cal_mag_array)

119.61187232043481


## Ejercicio 94

Write a NumPy program to count the frequency of unique values in NumPy array

In [ ]:
# Creamos el array con numeros repetidos

array_repeat = np.asarray([1, 1, 2, 2, 3, 3, 5, 6, 6, 7, 8, 9])

print(array_repeat,'\n')

# Ahora contamos los repetidos

"""

    Con return_counts -> devolvemos un array con el numero de veces que se 
    repite un numero dentro del array.

    Con return_index -> devolvemos un array con el numero de indices que se
    quedan en el nuevo array al pasar el metodo .unique.

"""

array_repeat_clean = np.unique(array_repeat, return_counts = True, return_index = True)

print(array_repeat_clean)

[1 1 2 2 3 3 5 6 6 7 8 9] 

(array([1, 2, 3, 5, 6, 7, 8, 9]), array([ 0,  2,  4,  6,  7,  9, 10, 11]), array([2, 2, 2, 1, 2, 1, 1, 1]))


## Ejercicio 95

Write a NumPy program to check whether the NumPy array is empty or not

In [ ]:
# Creamos un array vacio y otro con numeros.

array_empty = np.asarray([])
array_data = np.arange(0, 10, dtype = np.int8)

# Ahora comprobamos si los arrays están vacios o no

if array_empty.size == 0:
  print("The array is empty")
if array_data.size != 0:
  print("The array not empty")

The array is empty
The array not empty


## Ejercicio 96

Write a NumPy program to divide each row by a vector element

In [ ]:
# Creamos los arrays 

array_normal = np.arange(100, 110)

array_divider = np.asarray([2])

# Ahora dividimos cada elemento del primer array con array_divider

divider_array = array_normal / array_divider[:, None]

print(divider_array)

[[50.  50.5 51.  51.5 52.  52.5 53.  53.5 54.  54.5]]


## Ejercicio 97

Write a NumPy program to print all the values of an array

In [ ]:
# Creamos un array para despues sacar los valores 1 a 1

array_97 = np.random.randint(0, 10, size = 10)

print(array_97, "\n")

# Sacamos los valores del array 1 a 1

for number in range(len(array_97)):
  print(f"The number in the position index {number} is {array_97[number]}")

[3 0 1 5 3 3 1 8 2 5] 

The number in the position index 0 is 3
The number in the position index 1 is 0
The number in the position index 2 is 1
The number in the position index 3 is 5
The number in the position index 4 is 3
The number in the position index 5 is 3
The number in the position index 6 is 1
The number in the position index 7 is 8
The number in the position index 8 is 2
The number in the position index 9 is 5


## Ejercicio 98

Write a NumPy program to convert the raw data in an array to a binary string and then create an array

In [ ]:
# Creamos un array para pasarlo a binario despues

new_array = np.arange(0, 10, dtype = np.int8)

print(new_array, '\n')

# Pasamos el array a binario

new_binary_array = new_array.tobytes()

print(new_binary_array, '\n')

# Y ahora lo reconvertimos de binario a array

"""

    !Ojo de nuevo con .frombuffer, para que no de error hay que indicarle el
    argumento de dtype, para indicarle que tipo de salida queremos en los datos
    si int, float, bool, string...

"""

extract_binary_array = np.frombuffer(new_binary_array, dtype = np.int8)

print(extract_binary_array)

[0 1 2 3 4 5 6 7 8 9] 

b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t' 

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 99

Write a NumPy program to sum and compute the product of a NumPy array elements.

In [ ]:
# Creamos un array 

array_calculate = np.random.randint(0, 100, size = 10, dtype = np.int16)

print(array_calculate, '\n')

# Ahora hacemos la suma de todos los numeros

sumatorio = array_calculate.sum()

print(sumatorio, '\n')

product = array_calculate.cumsum()

print(product.sum())

[70 46 44 39 71 10 86 86 30 21] 

503 

2898


## Ejercicio 100

Write a NumPy program to take values from a source array and put them at specified indices of another array.

In [ ]:
# Creamos el array

array_100 = np.asarray([ 10., 10., 20., 30., 30.])

print(array_100)

# Ahora sustituimos el index 0 y el index ultimo por 0 y 40

array_100[0] = 0
array_100[-1] = 40

print(array_100)


[10. 10. 20. 30. 30.]
[ 0. 10. 20. 30. 40.]
