<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/Numpy_bonus_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bonus Exercices

## Exercices 21

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [ ]:
# Import numpy
import numpy as np

In [ ]:
# Crear un array de 10 valores de longitud de entre el 5 y el 50

range_array = np.linspace(6, 49, num = 10, dtype = np.int8)
print(range_array)

[ 6 10 15 20 25 29 34 39 44 49]


## Exerciices 22

Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
# Primero creamos el array

range_array = np.arange(0, 21, dtype = np.int8)

print(range_array)

# Segundo filtramos la parte del array que queremos pasar a negativo y lo multiplicamos por -1

range_array[9: 15] *= -1

print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14  15  16  17
  18  19  20]


## Exercices 23

Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [ ]:
# Crear un array de 5 de longitud con enteros aleatorios entre 0 y 10

range_array = np.random.randint(0, 10, size = 5, dtype = np.int8)
print(range_array)



[1 7 3 0 1]


## Exercices 24

Write a NumPy program to multiply the values of two given vectors.

In [ ]:
# Creamos el array 1

array_1 = np.random.randint(0, 10, size = 5, dtype = np.int8)
print(array_1, "\n")

# Creamos el array 2

array_2 = np.random.randint(5, 15, size = 5, dtype = np.int8)

print(array_2, "\n") 

# Ahora multiplicamos los dos arrays

array_total = array_1 * array_2

print(f"Multiplicar los arrays da el siguiente array: {array_total}")


[7 1 2 0 6] 

[11 11  7  7  5] 

Multiplicar los arrays da el siguiente array: [77 11 14  0 30]


## Exercices 25

Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [ ]:
# Aquí podemos concatenar 2 metodos, arange con reshape.

array_matriz = np.arange(10, 22, dtype = np.int8).reshape(3, 4)

print(array_matriz)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


## Exercices 26

Write a NumPy program to find the number of rows and columns of a given matrix

In [ ]:
# Para este ejercicio vamos a usar la matriz del anterior ejercicio

print(array_matriz.shape)

(3, 4)


## Exercices 27

Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [ ]:
# Para este ejercicio vamos a usar el metodo indetity

diagonal_array = np.identity(3)
print(diagonal_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Exercices 28

Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [ ]:
# Creamos primero la matriz de 10 x 10

matrix_ten = np.ones((10, 10), dtype = np.int8)

# Ahora cambimos los unos centrales por ceros

matrix_ten[1:-1, 1:-1] = 0

print(matrix_ten)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Exercices 29

Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
# Aquí usaremos el metodo diag donde le pasaremos el array de 1 al 5 para la diagonal

matrix_five = np.diag([1, 2, 3, 4, 5])

print(matrix_five)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## Exercices 30

Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [ ]:
# Creamos la matriz de 4 x 4 primero

matriz_zeros = np.ones((4, 4), dtype = np.int8)

print(matriz_zeros)

# Ahora aplicamos los sliders correspondientes para modificar la matriz

matriz_zeros[::2, ::2] = 0
matriz_zeros[1::2, 1::2] = 0

print(matriz_zeros)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
