<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/Numpy_bonus_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercices

## Exercices 11

Write a NumPy program to convert a list and tuple into arrays. 

List to array:

`[1 2 3 4 5 6 7 8]`

Tuple to array:

```
[[8 4 6]
[1 2 3]]
```

In [ ]:
# import numpy

import numpy as np

In [ ]:
# Parte 1 - convertir una lista a array
my_list_array = [1, 2, 3, 4, 5, 6, 7, 8]
print(type(my_list_array), "\n")

my_list_array = np.asarray(my_list_array)
print(my_list_array)
print(type(my_list_array), "\n")

# Parte 2 - Pasar tupla a array()

my_tuple = ([8, 4, 6], [1, 2, 3])
print(type(my_tuple), "\n")

tupla_array = np.asarray(my_tuple)
print(tupla_array)
print(type(tupla_array), "\n")

# Parte 3 - Para practicar

# Primero creamos la lista

my_list = [1, 2, 3, 4, 5, 6, 7, 8]

# Ahora devemos de eliminamos el 5 y el 7

def remove_odd(my_list):
  for num in my_list:
    if num >= 5 and num % 2 != 0:
      my_list.remove(num)

remove_odd(my_list)
print(my_list, "\n")

# Por último lo pasamos a array de 2 x 2

my_list = np.array(my_list, dtype = np.int8).reshape(2,3)

# Ahora le damos la vuelta

my_list = my_list[::-1]
print(my_list)

<class 'list'> 

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'> 

<class 'tuple'> 

[[8 4 6]
 [1 2 3]]
<class 'numpy.ndarray'> 

[1, 2, 3, 4, 6, 8] 

[[4 6 8]
 [1 2 3]]


## Exercices 12

Write a NumPy program to append values to the end of an array. 
Expected Output:

Original array:

`[10, 20, 30]`

After append values to the end of the array:

`[10 20 30 40 50 60 70 80 90]`

In [ ]:
from numpy.core.fromnumeric import size
# Creamos el array

my_array = np.array([10, 20, 30])

# Ahora añadimos los numeros del 40 al 90 de 10 en diez

# Primero creamos los numeros del 40 al 90

add_array = np.arange(40, 100, 10, dtype = np.int8)
print(add_array)

# Por último utilizamos el metodo append para uniificar los 2 arrays

my_array = np.append(my_array, add_array)

print(my_array)
print((my_array).dtype)

[40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]
int64


## Exercices 13

Write a NumPy program to create an empty and a full array. 

Expected Output:

```python
# empty array
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]

# full array
[[6 6 6]
[6 6 6]
[6 6 6]]
```

In [ ]:
# Creamos un array con el metodo empty

array_empty = np.empty((3,3))
print(array_empty, "\n")

# Creamos un array con numeros enteros

array_full = np.full((3, 3), 6)
print(array_full)

[[4.05667341e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 2.46151512e-312 2.52905473e-052]
 [1.14195399e-071 4.22086166e-090 9.76875305e+165]] 

[[6 6 6]
 [6 6 6]
 [6 6 6]]


## Exercices 14

Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array. 

Sample Array 

`[0, 12, 45.21, 34, 99.91]`

`[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]`

Expected Output:

Values in Fahrenheit degrees:
`[ 0. 12. 45.21 34. 99.91]`

Values in Centigrade degrees:
`[-17.78 -11.11 7.34 1.11 37.73 0. ]`

Values in Centigrade degrees:
`[-17.78 -11.11 7.34 1.11 37.73 0. ]`

Values in Fahrenheit degrees:
`[-0. 12. 45.21 34. 99.91]`

In [ ]:
# Creamos los arrays

cel = np.array([17.78, -11.11, 7.34, 1.11, 37.73, 0.])

fah = np.array([0., 12., 45.21, 34., 99.91])
# Convertimos los celsius en fahrenheit

fahrenheit = np.round((cel * 1.8) + 32, 2)
print(fahrenheit)

# Convertimos los fahrenheit en celsius

celsius = np.round(((fah - 32) / 1.8),2)
print(celsius)

[64.   12.   45.21 34.   99.91 32.  ]
[-17.78 -11.11   7.34   1.11  37.73]


## Exercices 15

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

Original array:`x [ 1.00000000+0.j]`


Original array:`y [ 0.70710678+0.70710678j]`

Real part of the array:
```python
[ 1.]
[ 0.70710678]
```
Imaginary part of the array:
```python
[ 0.]
[ 0.70710678]
```

In [ ]:
# Primero usamos el metodo .sqrt para devolver la raíz cuadrada no negativa de la matriz
  
complex_1 = np.sqrt([1.00000000+0.j])
complex_2 = np.sqrt([0.70710678+0.70710678j])

print(complex_1)
print(complex_2, "\n")

# Segundo sacamos la parte real del numero complejo con el metodo .real

real_array_1 = complex_1.real
print(real_array_1)
real_array_2 = complex_2.real
print(real_array_2, "\n")

# Tervero sacamos la parte imaginaria del numero complejo con el metodo .imag

imag_array_1 = complex_1.imag
print(imag_array_1)
imag_array_2 = complex_2.imag
print(imag_array_2)

[1.+0.j]
[0.92387953+0.38268343j] 

[1.]
[0.92387953] 

[0.]
[0.38268343]


## Exercices 16

 Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Expected Output:

Size of the array: 3

Length of one array element in bytes: 8

Total bytes consumed by the elements of the array: 24

In [ ]:
# Primero creamos el array

my_array = np.array([8, 19, 4])

# Segundo sacamos la longitud con .size

print(f"La longitud del array es de {my_array.size}")

# Tercero sacamos el peso de cada elemento del array en bytes

print(f"La longitud del array es de {my_array.itemsize}")

# Cuarto sacamos el peso total del array en bytes

print(f"La longitud del array es de {my_array.itemsize * my_array.size}")

La longitud del array es de 3
La longitud del array es de 8
La longitud del array es de 24


## Exercices 17

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

Expected Output:

Array1: `[ 0 10 20 40 60]`

Array2: `[0, 40]`

Compare each element of array1 and array2

`[ True False False True False]`

In [ ]:
# Primero creamos los arrays
array_1 = np.array([0, 10, 20, 40, 60])

array_2 = np.array([0, 40])

# A continuación vamos a usar el metodo .in1d 

"""

  .in1d -> Comprueba si cada elemento de una matriz 1-D,
           está también presente en una segunda matriz.

"""
eq_array = np.in1d(array_1, array_2)

print(eq_array)

[ True False False  True False]


## Ejercicio 18

Write a NumPy program to find common values between two arrays. 

Expected Output:

Array1: `[ 0 10 20 40 60]`

Array2: `[10, 30, 40]`

Common values between two arrays:

`[10 40]`

In [ ]:
# Primero creamos los arrays

array_1 = np.array([0, 10, 20, 40, 60])

array_2 = np.array([10, 30, 40])

# Ahora vamos a usar el metodo .unique 

"""
  .intersect1d -> Encuentra la intersección de dos matrices, 
             devuelve los valores únicos y ordenados 
             que se encuentran en ambas matrices de entrada.

"""

uniq_array = np.intersect1d(array_1, array_2)

print(uniq_array)


[10 40]


## Exercices 19

 Write a NumPy program to get the unique elements of an array. 

Expected Output:

Original array:

[10 10 20 20 30 30]

Unique elements of the above array:

[10 20 30]

Original array:

[[1 1]
[2 3]]

Unique elements of the above array:

[1 2 3]

In [ ]:
# Primero creamos los arrays

array_1 = np.array([10, 10, 20, 20, 30, 30])

array_2 = np.array([[1, 1], [2, 3]])

# A continuación vamos a usar el metrodo .unique para sacar un array sin valores repetidos

"""
  .unique -> Encuentra los elementos únicos de un array y 
             devuelve dichos elementos únicos ordenados de un array. 
             
    Hay tres salidas opcionales además de los elementos únicos:

      -Los índices del array de entrada que dan los valores únicos

      -Los índices del array único que reconstruyen el array de entrada

      -El número de veces que aparece cada valor único en el array de entrada

"""

# Sacamos el array con valores unicos para el primer caso:
new_array = np.unique(array_1)

print(new_array, "\n")

# Sacamos el array con valores unicos para el segundo caso:
new_array = np.unique(array_2)

print(new_array)

[10 20 30] 

[1 2 3]


## Exercices 20

Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. 

Expected Output:

Array1: `[ 0 10 20 40 60 80]`

Array2: `[10, 30, 40, 50, 70, 90]`

Set difference between two arrays:

`[ 0 20 60 80]`

In [ ]:
## Primero creamos los arrays

array_1 = np.array([ 0, 10, 20, 40, 60, 80])

array_2 = np.array([10, 30, 40, 50, 70, 90])

# Para este ejercicio vamos a usar el metodo .setdiff1d

"""

  .setdiff1d -> Encuentra la diferencia de conjuntos de dos arrays y 
                devuelve los valores únicos en ar1 que no están en ar2.

"""

# A continuación usamos el metodo

new_array = np.setdiff1d(array_1, array_2)

print(new_array)


[ 0 20 60 80]
