<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/NumPy_Arrays_exercices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# NumPy Arrays Exercices

## Exercices 1

Write a NumPy program to print the NumPy version in your system

In [ ]:
# Imprimos la version de Numpy

version = np.__version__
print(f"La versión de Numpy es la {version}")

La versión de Numpy es la 1.21.6


## Exercices 2

Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array. 

Expected Output:

Original List: `[12.23, 13.32, 100, 36.32]`

One-dimensional NumPy array: `[ 12.23 13.32 100. 36.32]`

In [ ]:
list_exercices_2 = [12.23, 13.32, 100, 36.32]

# Creamos el array con np.array

"""
  NOTA: le he metido no.float16 para ir acostumbrandome a escribir codigo efi-
  ciente, con float16 usamos menos memoria que la dada por defecto.

"""

new_array = np.array(list_exercices_2, dtype = np.float16)

print(new_array)

[ 12.23  13.32 100.    36.3 ]


## Exercices 3

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

`[[ 2 3 4]

[ 5 6 7]

[ 8 9 10]]`

In [ ]:
# Aquí vamos a usar una concatenación de dos modulos, arange y reshape

"""
  1. con np.range(2, 11) generamos el array con los numeros del 2 al 10, 
  siempre hay que tener en cuenta que el útlimo numero no se incluye en laç
  generación

  2. Con reshape le decimos que queremos una matriz de 3 x 3 

"""

new_array = np.arange(2, 11).reshape(3, 3)

print(new_array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Exercices 4

Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

`[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]`

Update sixth value to 11

`[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]`

In [ ]:
# Primero creamos un array con 10 ceros, por defecto siempre son float

vector_null = np.zeros(10, dtype = np.float16)

print(vector_null)

# A continuación sustituimos la sexta posición por un 11

vector_null[6] = 11

print(vector_null)

# Otra forma de hacerlo, pero mas complejo y que puede producir perdida de datos

vector_null_2 = np.zeros(10, dtype = np.float16)

rewrite_vector = np.insert(vector_null_2, [6], 11)
rewrite_vector = np.delete(rewrite_vector, [7])

print(rewrite_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


## Exercices 5
Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:
`[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]`

In [ ]:
# Aquí usaremos el modulo de arange

rang_array = np.arange(12, 38, dtype = np.int8)

print(rang_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


## Exercices 6
Write a NumPy program to reverse an array (first element becomes last). 
Original array:

`[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]`

Reverse array:

`[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]`

In [ ]:
# Aqui usaremos [:: -1] para darle la vuelta al array

rang_array = rang_array[:: -1]

print(rang_array)


[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## Exercices 7

Write a NumPy program to convert an array to a float type.

Sample output:

Original array

`[1, 2, 3, 4]`

Array converted to a float type:

`[ 1. 2. 3. 4.]`

In [ ]:
from numpy.core.getlimits import array
# Creamos el array tipo int

array_int = np.arange(1, 5, dtype = np.int8)

print(array_int)

# Ahora lo pasamos a float

array_float = np.array(array_int, dtype = np.float16)

print(array_float)

[1 2 3 4]
[1. 2. 3. 4.]


## Exercices 8

Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
Expected Output:

Original array:

```
[[ 1.  1.  1.  1.  1.] 

 [ 1.  1.  1.  1.  1.]

 [ 1.  1.  1.  1.  1.]

 [ 1.  1.  1.  1.  1.]

 [ 1.  1.  1.  1.  1.]]
 ```                                                 

1 on the border and 0 inside in the array

```
[[ 1.  1.  1.  1.  1.]

 [ 1.  0.  0.  0.  1.]                                                  

 [ 1.  0.  0.  0.  1.]                                                  

 [ 1.  0.  0.  0.  1.]                                                  

 [ 1.  1.  1.  1.  1.]]
```


In [ ]:
# Creación de array 2d

array_1 = np.ones((5, 5))
print(array_1)

# Ahora sustituimos los 1 centrales de las filas 1,2,3

array_1[1:-1, 1:-1] = 0

print(array_1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Exercices 9

Write a NumPy program to add a border (filled with 0's) around an existing array.

Expected Output:

Original array:

```
[[ 1.  1.  1.]                                                          
 [ 1.  1.  1.]                                                          
 [ 1.  1.  1.]] 
```                                                       

1 on the border and 0 inside in the array                               

```
[[ 0.  0.  0.  0.  0.]                                                  
 [ 0.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  0.]                                                  
 [ 0.  0.  0.  0.  0.]]
```

In [ ]:
# Creamos el array con unos

array_1s = np.ones((3, 3))

print(array_1s)

# Ahora lo que debemos hacer es rellenar con ceros alrededor de los unos

"""
  modulo pad

  Para hacer esta operación vamos a usar el modulo pad, este modulo lo que nos
  permite es rellenar el array con lo que deseemos, en este caso ceros(0)

  padding_func(vector, iaxis_pad_width, iaxis, kwargs)

  vector -> vector es el array al que le queremos agregar
  
  iaxis_pad_width -> es la cantidad que queremos que se le agregue,
  contra mayor sea el numero mas numeros agregara
  
  mode="constant" -> Le indicamos que los valores con los que rellene sean
  los mismos

  constant_values=0 -> y aquíi indicamos el numero con el queremos que rellene

"""

add_zero = np.pad(array_1s, pad_width=1, mode="constant", constant_values=0)

print(add_zero)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Exercices 10

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

Checkerboard pattern:

Checkerboard pattern:   

`[[0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]   

 [0 1 0 1 0 1 0 1] 

 [1 0 1 0 1 0 1 0] 

 [0 1 0 1 0 1 0 1] 

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1] 
                                                      
 [1 0 1 0 1 0 1 0]]`

In [ ]:
# Creamos la matriz de 8 x 8 llena de ceros:

matriz_eight = np.zeros((8, 8), dtype = np.int8)

# Ahora sustituimos los ceros por unos de los arrays impares

matriz_eight[::2, ::2] = 1

# Ahora sustituimos los ceros por unos de los arrays impares

matriz_eight[1::2, 1::2] = 1

print(matriz_eight)

# Ejercicio igual pero con unos al principio sustituidos por ceros

# Creamos la matriz de 8 x 8 llena de unos:

matriz_eight = np.ones((8, 8), dtype = np.int8)

# Ahora sustituimos los ceros por unos de los arrays impares

matriz_eight[1::2, ::2] = 0

# Ahora sustituimos los ceros por unos de los arrays impares

matriz_eight[::2, 1::2] = 0

print(matriz_eight)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
