<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/NumPy_Exercices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercices



In [ ]:
# Import numpy librery
import numpy as np

## Exercice 1 
### Write a NumPy program to get the numpy version and show numpy build configuration

In [ ]:
# numpy version
print(np.__version__)

# numpy build configuration, call show_config() function
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

## Exercices 2



In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## Exercices 3

Write a NumPy program to test whether none of the elements of a given array is zero

In [ ]:
my_array = np.empty(10, dtype=np.int8)

# Con np.all vemos si todos los valores del array son True, es decir mayor que 0.

print(np.all(my_array)) 


False


## Exercices 4

Write a NumPy program to test whether any of the elements of a given array is non-zero

In [ ]:
#Con np.any vemos si alguno de los valores del array es True, es decir mayor que 0.
print(np.any(my_array))

True


## Exercices 5

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [ ]:
my_array = np.array([0, -10, 20, np.nan, np.inf]) 

'''Con np.isfinite sacamos en formato booleano si un numero es finito,
es decir True si es diferente de NaN o infinito'''

print(np.isfinite(my_array)) 

[ True  True  True False False]


## Exercices 6

Write a NumPy program to test element-wise for positive or negative infinity

In [ ]:
my_array = np.array([0, -10, 20, np.nan, np.inf]) 

'''Con np.isinf sacamos en formato booleano si un numero es infinito,
tanto positivo, como negativo, es decir True si es un valor infinito

True where x == +/-inf, otherwise False.

'''

print(np.isinf(my_array)) 

inf
[False False False False  True]


## Exercices 7

Write a NumPy program to test element-wise for NaN of a given array


In [ ]:
""" Con isnan lo que sacamos es si un valor dentro del array es NaN, 
es decir True para NaN y False para el resto"""

print(np.isnan(my_array))

[False False False  True False]


## Exercices 8

Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not

In [ ]:
my_array = np.array([0, -10, 20, np.nan, np.inf, 2j])

"""Para numeros complejos usamos np.iscomplex,
esto nos devolvera un valor booleano donde si hay un numero complejo
devolvera True.

es_numero_complejo = 1j
"""

print(np.iscomplex(my_array))

# Para saber si el array contiene numeros reales, y no complejos.

print(np.isreal(my_array))

""" Para saber si un numero es escalable 

Ejemplos:

np.isscalar(3.1) # Float
True
np.isscalar(np.array(3.1)) # Al ser array no es escalable
False
np.isscalar([3.1]) # Al ser lista no es escalable
False
np.isscalar(False) # Boolean
True
np.isscalar('numpy') # String
True

"""
# En este caso al ser un array no es numero escalable
print(np.isscalar(my_array)) 

"""Pero si lo hacemos sobre un valor del array podemos saber si este es 
escalable.

""" 
print(f"{np.isscalar(my_array[2])}, este numero es escalable")

# Si son listas, tuplas o diccionario no son escalables
no_escalable = {"hola": 3.1}
print(f"{np.isscalar(no_escalable)}, este numero es no escalable") 




[False False False False False  True]
[ True  True  True  True  True False]
False
True, este numero es escalable
False, este numero es no escalable


## Exercices 9

Write a NumPy program to test whether two arrays are element-wise equal within a tolerance


In [ ]:
my_array_1 = [1, 2, 3]
my_array_2 = [1, 2, 3]
my_array_dif = [1, 2, 4]


# Con allclose comparamos si 2 arrays son iguales y tienen valores tolerantes
"""
Los valores de tolerancia son positivos, normalmente números muy pequeños. 

"""
# Comparamos 2 arrays iguales
print(np.allclose(my_array_1, my_array_2))

# Comparamos 2 arrays diferentes
print(np.allclose(my_array_1, my_array_dif))

True
False


## Exercices 10

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [ ]:
array_a = np.array([5, 3, 2])
array_b = np.array([3, 5, 2])

# Uso de greater (mayor que)

"""

 Su funcionamiento es el siguiente If x1.shape != x2.shape

 .shape -> esto saca las columnas y filas de cada uno de los 2 arrays y compara
 si son diferentes, devolviendo valores booleanos

  operacion que realiza
  
  a = np.array([4, 2])
  b = np.array([2, 2])
  a > b
  array([ True, False])

"""

print(np.greater(array_a, array_b))

# Uso de greater_equal (mayor o igual que)

"""

  Aqui el funcionamiento es el mismo que el de greater, pero tambien nos compara
  si son iguales en ambos shape, devolviendo valores booleanos

  operación que realiza

  a = np.array([4, 2, 1])
  b = np.array([2, 2, 2])
  a >= b
  array([ True,  True, False])

"""

print(np.greater_equal(array_a, array_b))

# Uso de less (menor que)

"""

  less nos proporcina la comparacion si es menor que,
  devolviendo valores booleanos

  operación que realiza:

  a = np.array([1, 2])
  b = np.array([2, 2])
  a < b
  array([ True, False])


"""

print(np.less(array_a, array_b))

# Uso de less_equal (menor o igual que)

"""

  less_equal hace lo mismo que less pero añadiendo si son iguales que, 
  devolviendo valores booleanos

  operación que realiza:

  a = np.array([4, 2, 1])
  b = np.array([2, 2, 2])
  a <= b
  array([False,  True,  True])

"""

print(np.less_equal(array_a, array_b))

[ True False False]
[ True False  True]
[False  True False]
[False  True  True]


## Exercices 11

Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays


In [ ]:
 # Uso de equal o igual que

 """
  Con equal, comparamos si cada valor del array es igual a otro valor de otro
  array, por ejemplo:

  a = np.array([2, 4, 6])
  b = np.array([2, 4, 2])
  a == b
  array([ True,  True, False])

 """
 print(np.equal(array_a, array_b))

 # Uso not_equal o distinto de

 """
  Con not_equal, lo que comparamos si los valores son distintos en cada posición
  de los array, devolviendo valores booleanos

 """

 print(np.not_equal(array_a, array_b))

[False False  True]
[ True  True False]


## Ejercicio 12

Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [ ]:
# Para este caso necesitamos realizar una operacion para cada valor del array

array_peso = np.array([1, 7, 13, 105])

"""

  1. Lo primero que tenemos que hacer es sacar el tamaño en memoria
  de todo el array, usaremos size concatenandolo con el nombre de nuestro array.

  array_peso.size

  * El resultado se expresa en bytes

"""

print(array_peso.size)

"""
  2. Ahora, debemos de sacar lo que ocupa cada elemento del array en memoria,
  para ello usaremos itemsize concatenandolo con el nombre de nuestro array

  array_peso.itemsize

"""

print(array_peso.itemsize)

"""
  3. Por último realizamos el calculo total de espacio que ocupa en memoria,
  multiplicando el tamaño en memoria total del array con el de cada elemento
  del array

  array_peso.size * array_peso.itemsize

"""
print(array_peso.size * array_peso.itemsize)


4
8
32


## Exercices 13

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [ ]:
# Para 10 ceros

zeros = np.zeros(10)
print(zeros)

# Para 10 unos

ones = np.ones(10)
print(ones)

# Para 10 cincos

fives = np.ones(10) * 5
print(fives)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Exercices 14

Write a NumPy program to create an array of the integers from 30 to 70

In [ ]:
# Crear un array con enteros del 30 al 70

array_rang = np.arange(30, 71, dtype = np.int8)
print(array_rang)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## Exercices 15

Write a NumPy program to create an array of all the even integers from 30 to 70

In [ ]:
# Crear un array con los pares enteros desde 30 al 70

array_rang_even = np.arange(30, 70, 2, dtype = np.int8)
print(array_rang_even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


## Exercices 16

Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
# Crear una matriz de identidad de 3 x 3 

"""
  La matriz de identidad es una matriz cuadrada con unos en la 
  diagonal principal.

  ejemplo:

  array([[1.,  0.,  0.],
       [0.,  1.,  0.],
       [0.,  0.,  1.]])

"""

print(np.identity(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Exercices 17

Write a NumPy program to generate a random number between 0 and 1

In [ ]:
# Genera numeros aleatorios entre el 0 y el 1

"""
  1. Podemos hacerlo con np.random.normal(loc, scale, size)

  array_random = np.random.normal(0.0, 1.0, size = (1, 4))

  Pero no nos devolveria un valor entre 0 y 1, ya que dependediendo del
  calculo puede sacar valores por debajo o por encima de 1

  2. Para que los valores salgan entre 0 y 1 sin tener el problema del
  punto 1, podemos usar random.rand

  3. Podemos comprobar que realmente se estan generando numeros entre 0 y 1,
  usando las funciones de min y max

"""

array_random = np.random.rand(5)

print(array_random)
print(np.max(array_random))
print(np.min(array_random))


[0.06711896 0.55080362 0.73276297 0.27302971 0.05240838]
0.7327629728324241
0.052408382738796444


## Exercices 18

Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [ ]:
# En este caso no se nos pide que sea un rango de 0 a 1, y podemos usar random.normal
array_normal_dist = np.random.normal(10, 5, size = (1, 15))
print(array_normal_dist)

[[ 3.83703597  7.63533474 10.64416617 12.14243511 12.27478059  6.19474933
   3.84793628 17.50456415  3.41081413 13.69168667  7.75887435 17.61005763
   7.02835591  5.20146741 13.72396024]]


## Exercices 19

Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [ ]:
# Aquí generamos los numeros aleatorios de entre 15 y 55
new_array_random = np.arange(15, 55)

# Por último pintamos el array sin el primer valor y sin el último
print(new_array_random[1: -1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


## Exercices 20 

Write a NumPy program to create a 3X4 array using and iterate over it

In [ ]:
# Primero creamos la matriz

nueva_matriz = np.arange(0, 12).reshape(3, 4)
print(nueva_matriz)

# Ahora iteramos sobre ella para sacarla como una linea

"""
 Lo que voy a usar ahora es la función nditer, 
 que proporciona muchas formas flexibles de ver todos los elementos de una 
 o más matrices de forma sistemática.

"""

for num in np.nditer(nueva_matriz):
  print(num, end = " ")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 