<a href="https://colab.research.google.com/github/Legodark/Learning-Data-Science/blob/import_colab/colab_notebooks/Numpy/Numpy_bonus_arrays_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importacion de Numpy

In [2]:
import numpy as np

# Bonus Exercices Array 2

[Enlace](https://www.w3resource.com/python-exercises/numpy/index-array.php)

## Ejercicio 61

Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.

In [ ]:
# Creamos el array de 14 elementos

array_14_elements = np.random.randint(0, 100, size = 14)
print(array_14_elements)

[ 8 81 80 29 40 70 60 50 62 98 20 48  9 26]


In [ ]:
# A continuación dividimos el array en 3 arrays, uno de 2, otro de 4 y otro de 8

""" 

    El funcionamiento de .split es el siguiente:
      -En el primer parametro pasamos el array que queremos seccionar.
      -El segundo parametro indicamos las divisiones que se haran en 
       forma de split, para el caso de los valores que pasamos seríia
       asíi:
       
       ary[:2]
       ary[2:6]
       ary[6:] 


"""
my_array_split = np.split(array_14_elements, [2, 6])
print(my_array_split)

[array([ 8, 81]), array([80, 29, 40, 70]), array([60, 50, 62, 98, 20, 48,  9, 26])]


## Ejercicio 62

Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis



In [ ]:
# Creamos el array.

array_spl = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[12, 13, 14, 15]])
print(array_spl)

np.hsplit(array_spl, [2, 6])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]), array([], shape=(4, 0), dtype=int64)]

## Ejercicio 63

Write a NumPy program to get the number of nonzero elements in an array

In [ ]:
# Cremos el array con numeros que tengan ceros.

my_array = np.asarray([10, 1000, 250, 500, 0]) # el 0 solo no se cuenta.

np.count_nonzero(my_array)

4

## Ejercicio 64

Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
# Primero vamos a crear un array de ceros

array_zeros = np.zeros([5, 5])
print(array_zeros, "\n")

# Ahora concatenemos e iigualamos con un arange

array_zeros += np.arange(5)

print(array_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Ejercicio 65

Write a NumPy program to test whether specified values are present in an array


In [ ]:
# Creamos el array

array_random_1 = np.random.randint(0, 100, size = 10)

print(array_random_1, "\n")

# Con isin, miramos si alguno de los valores que le pasamos como segundo parametro estan en nuestro array.

array_random_1[np.isin(array_random_1, [10, 23, 12, 65, 50])]

[61 11 59 15 97  5 94  3 76 38] 



array([], dtype=int64)

## Ejercicio 66

Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
# Creamos el array con 10 numeros del 0 al 1 sin incluir ninguno de los 2.

num_randoms = np.random.rand(10)
print(num_randoms)

[0.6420233  0.84663594 0.94247535 0.49892661 0.00325146 0.61820692
 0.00691393 0.83030877 0.54443174 0.12791374]


## Ejercicio 67

Write a NumPy program to make an array immutable (read-only)

In [ ]:
# Creamos un array que despues haremos que solo pueda ser leido y no modificado

array_immutable = np.random.randint(0, 20, size = 20)

print(array_immutable, "\n")

# Ahora convertimos el array en Immutable

array_immutable.flags.writeable = False

# Probamos que no se puede sobrescribir

array_immutable[0] = 20

[ 8  9 10  2 10 18 13  8  1  5  6  8  5 19 17  4  4 12  1  5] 



ValueError: ignored

## Ejecicio 68

Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100

In [10]:
# Creamos un array 

my_array = np.arange(0, 100)

# Sacamos los multiplos de 3 y de 5

multiply_array = my_array[(my_array % 3 == 0) | (my_array % 5 == 0)]

print(multiply_array.sum())

2318


## Ejercicio 69

Write a NumPy program to create an array with 10^3 elements.

In [13]:
# Creamos el array

array_2 = np.arange(0, 10)

print(array_2, "\n")

# A continuación lo elevamos a al cubo ^ 3

array_power = np.power(array_2, 3)

print(array_power)

[0 1 2 3 4 5 6 7 8 9] 

[  0   1   8  27  64 125 216 343 512 729]


## Ejercicio 70

Write a NumPy program to create display every element of a NumPy array

## Ejercicio 71

Write a NumPy program to create and display every element of a NumPy array in Fortran order



## Ejercicio 72

Write a NumPy program to create a 5x5x5 cube of 1's

## Ejercicio 73

Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array. 

In [17]:
# Creamos el array

nuevo_array = np.arange(0, 12).reshape(3, 4)

print(nuevo_array, "\n")

multiply_3 = np.multiply(nuevo_array, 3)

print(multiply_3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## Ejercico 74

Write a NumPy program to combine a one and a two dimensional array together and display their elements

In [38]:
# Creamos 2 array, uno de 1 dimensión y otro de 2

array_1D = np.arange(0, 5)

array_2D = np.array([np.random.randint(0, 100, size = 5), np.arange(10, 15)])

print(array_1D, "\n")
print(array_2D, "\n")

# Ahora unimos el array 1D con el array 2D

union_array = np.union1d(array_1D, array_2D)

print(union_array)

[0 1 2 3 4] 

[[86 10 58 22 60]
 [10 11 12 13 14]] 

[ 0  1  2  3  4 10 11 12 13 14 22 58 60 86]


## Ejercicio 75

Write a NumPy program to create an array of zeros and three column types (integer, float, character)

In [ ]:
#

## Ejercicio 76

 Write a NumPy program to create a function cube which cubes all the elements of an array

## Ejercicio 77

Write a NumPy program to create an array of (3, 4) shape and convert the array elements in smaller chunks.

## Ejercicio 78

Write a NumPy program to create a record array from a (flat) list of arrays

## Ejercicio 79

Write a NumPy program to generate a generic 2D Gaussian-like array

## Ejercicio 80

Write a NumPy program to convert a NumPy array into Python list structure.

In [42]:
# Creamos el array

new_array = np.random.randint(0, 100, size = 10, dtype = np.int16)

print(new_array)

[29 95 83 98 24 21 53 62 97 23]


In [45]:
# Ahora pasamos el array a lista

new_list = new_array.tolist()

print(new_list, "\n")
print(type(new_list))

[29, 95, 83, 98, 24, 21, 53, 62, 97, 23] 

<class 'list'>


## Ejercicio 81

Write a NumPy program to access an array by column

In [6]:
# Creamos el array y filtramos por columnas

array_access = np.array([[2, 3, 4, 5], [8, 9, 10, 11], [12, 13, 14, 15]])

print(array_access[:,0])
print(array_access[:,1])
print(array_access[:,2])
print(array_access[:,3])

[ 2  8 12]
[ 3  9 13]
[ 4 10 14]
[ 5 11 15]


## Ejercicio 82

Write a NumPy program to convert a NumPy array of float values to a NumPy array of integer values

In [11]:
# Creamos un array con flotantes

array_float = np.array([1, 2, 3, 4], dtype = np.float16)

print(array_float, '\n')

# A continuación le cambiamos el tipo de dato a int (entero)

array_convert = array_float.astype(int)

print(array_convert)

[1. 2. 3. 4.] 

[1 2 3 4]


## Ejercicio 83

Write a NumPy program to display NumPy array elements of floating values with given precision.

In [25]:
# Creamos un arra de entre 0 a 1

array_random = np.random.rand(10)

print(array_random, '\n')

[0.7  0.86 0.36 0.82 0.65 0.96 0.13 0.88 0.7  0.92] 



In [26]:
# Ahora ajustamos la preción de los decimales, por ejemplo a 1

np.set_printoptions(precision = 1)

print(array_random)

[0.7 0.9 0.4 0.8 0.6 1.  0.1 0.9 0.7 0.9]


## Ejercicio 84

Write a NumPy program to suppresses the use of scientific notation for small numbers in NumPy array.

## Ejercicio 85

Write a NumPy program to create a NumPy array of 10 integers from a generator.

In [29]:
# Creamos un array de 10 enteros

array_gen_int = np.random.randint(0, 100, size = 10)

print(array_gen_int)

[36  3 55 20 76 36 43 34 92 60]


## Ejercicio 86

Write a NumPy program to add an extra column to a NumPy array.

## Ejercicio 87

Write a NumPy program to find unique rows in a NumPy array

## Ejercicio 88

Write a NumPy program to replace all elements of NumPy array that are greater than specified array

## Ejercicio 89

Write a NumPy program to remove specific elements in a NumPy array.

## Ejercicio 90

Write a NumPy program to replace the negative values in a NumPy array with 0.

In [32]:
# Creamos un array con negativos

array_negative = np.arange(-10, 10)

print(array_negative)

# Arora reemplazamos los numeros negativos por 0

array_negative[array_negative < 0] = 0

print(array_negative)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[0 0 0 0 0 0 0 0 0 0 0 1 2 3 4 5 6 7 8 9]


## Ejercicio 91

Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

In [35]:
# Creamos un array con nan (not a number)

array_nan = np.array([10, np.nan, 20, 30, np.nan])

print(array_nan, '\n')

# Ahora limpiamos los nan de nuestro array

clean_nan = array_nan[np.logical_not(np.isnan(array_nan))]

print(clean_nan)

[10. nan 20. 30. nan] 

[10. 20. 30.]


## Ejercicio 92

Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

## Ejercicio 93

Write a NumPy program to get the magnitude of a vector in NumPy.

## Ejercicio 94

Write a NumPy program to count the frequency of unique values in NumPy array

In [41]:
# Creamos el array con numeros repetidos

array_repeat = np.asarray([1, 1, 2, 2, 3, 3, 5, 6, 6, 7, 8, 9])

print(array_repeat,'\n')

# Ahora contamos los repetidos

"""

    Con return_counts -> devolvemos un array con el numero de veces que se 
    repite un numero dentro del array.

    Con return_index -> devolvemos un array con el numero de indices que se
    quedan en el nuevo array al pasar el metodo .unique.

"""

array_repeat_clean = np.unique(array_repeat, return_counts = True, return_index = True)

print(array_repeat_clean)

[1 1 2 2 3 3 5 6 6 7 8 9] 

(array([1, 2, 3, 5, 6, 7, 8, 9]), array([ 0,  2,  4,  6,  7,  9, 10, 11]), array([2, 2, 2, 1, 2, 1, 1, 1]))


## Ejercicio 95

Write a NumPy program to check whether the NumPy array is empty or not

In [47]:
# Creamos un array vacio y otro con numeros.

array_empty = np.asarray([])
array_data = np.arange(0, 10, dtype = np.int8)

# Ahora comprobamos si los arrays están vacios o no

if array_empty.size == 0:
  print("The array is empty")
if array_data.size != 0:
  print("The array not empty")

The array is empty
The array not empty


## Ejercicio 96

Write a NumPy program to divide each row by a vector element

## Ejercicio 97

Write a NumPy program to print all the values of an array

In [56]:
# Creamos un array para despues sacar los valores 1 a 1

array_97 = np.random.randint(0, 10, size = 10)

print(array_97, "\n")

# Sacamos los valores del array 1 a 1

for number in range(len(array_97)):
  print(f"The number in the position index {number} is {array_97[number]}")

[3 0 1 5 3 3 1 8 2 5] 

The number in the position index 0 is 3
The number in the position index 1 is 0
The number in the position index 2 is 1
The number in the position index 3 is 5
The number in the position index 4 is 3
The number in the position index 5 is 3
The number in the position index 6 is 1
The number in the position index 7 is 8
The number in the position index 8 is 2
The number in the position index 9 is 5


## Ejercicio 98

Write a NumPy program to convert the raw data in an array to a binary string and then create an array

In [70]:
# Creamos un array para pasarlo a binario despues

new_array = np.arange(0, 10, dtype = np.int8)

print(new_array, '\n')

# Pasamos el array a binario

new_binary_array = new_array.tobytes()

print(new_binary_array, '\n')

# Y ahora lo reconvertimos de binario a array

"""

    !Ojo de nuevo con .frombuffer, para que no de error hay que indicarle el
    argumento de dtype, para indicarle que tipo de salida queremos en los datos
    si int, float, bool, string...

"""

extract_binary_array = np.frombuffer(new_binary_array, dtype = np.int8)

print(extract_binary_array)

[0 1 2 3 4 5 6 7 8 9] 

b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t' 

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 99

Write a NumPy program to sum and compute the product of a NumPy array elements.

In [78]:
# Creamos un array 

array_calculate = np.random.randint(0, 100, size = 10, dtype = np.int16)

print(array_calculate, '\n')

# Ahora hacemos la suma de todos los numeros

sumatorio = array_calculate.sum()

print(sumatorio, '\n')

product = array_calculate.cumsum()

print(product.sum())

[70 46 44 39 71 10 86 86 30 21] 

503 

2898


## Ejercicio 100

Write a NumPy program to take values from a source array and put them at specified indices of another array.

In [90]:
# Creamos el array

array_100 = np.asarray([ 10., 10., 20., 30., 30.])

print(array_100)

# Ahora sustituimos el index 0 y el index ultimo por 0 y 40

array_100[0] = 0
array_100[-1] = 40

print(array_100)


[10. 10. 20. 30. 30.]
[ 0. 10. 20. 30. 40.]
